### ISSUE TITLE
FAQ: What is OPA ()?

### ISSUE THREAD

**Issue by jonasmit** [kube-academy/backlog#11]
### Details

**Comment by jonasmit** [comment]
@dghant1024 - Will record this week and meet with @eitansuez

**Comment by jonasmit** [comment]
@dghant1024 - working on recording this week. should be ready for review this week with a demo

**Comment by lxie123** [comment]
@dghant1024

**Comment by djschny** [comment]
Where can the scripts be found? I tried looking in the two Google Drive folders and can't find anything:

* [Courses: In Progress](https://drive.google.com/drive/folders/1V1oAzdjlYEwC1ruCKRTEg_Fl1yxhvBoF)
* [Courses: Planning and Backlog](https://drive.google.com/drive/folders/1GOLSm4u1Z3-diNZTutaubDz77d6Q1hu0)

**Comment by djschny** [comment]
My bad this is part of the FAQ course:

https://drive.google.com/drive/folders/1eye1CLm8zul3-MRfcFz2-br-iKLoySWC?usp=sharing

**Comment by djschny** [comment]
I reviewed the recordings. In regards to overall slides, audio, and pace, it came out very nice. The volume level seems a bit lower than normal, but I don't think that should stop these videos, just something to look at for future recordings. In regards to feedback/suggestions:

* In total there is about 8 minutes worth of recordings which is too long for a FAQ lesson
* I would suggest we remove slide 2 and the associated recording as while it is nicely done it doesn't really help answer the question "What is OPA?" We can see this also illustrated as in the next slide/recording it starts out with an emphasis on "So... What is OPA?". Removing this would bring the length down to approximately 6.5 minutes.
* The rest of the content feels more like explaining how OPA works and is built versus explaining "what is OPA", so why does it exist, what's it's purpose, why would I use it, what problem does it solve, etc. I would suggest we focus on that and it would help make this FAQ lesson work well. The existing content would work better for a formal course on OPA or a series of FAQ lessons like "How is OPA architected?", "How is OPA integrated into Kubernetes?", etc.

**Comment by djschny** [comment]
Dwayne working on it this week.

**Comment by jonasmit** [comment]
@dghant1024 - 3 minute video recorded and will finalize his edits...

**Comment by lxie123** [comment]
@ 8 min  right now. Ask for advice on how to cut down. where to cut.

**Comment by dghant1024** [comment]
I have uploaded a video that needs to be edited.  I currently have ~8 minutes (if you subtract the introduction).  As you review this I will be editing too to narrow down the timing of the content.  

https://drive.google.com/file/d/11iwUym-vS6nx6lg-Wg8S5epblV5eL-G1/view?usp=sharing

@djschny : To keep things simple, please feel free to just give me the timings that need to be edited or taken out.

**Comment by djschny** [comment]
After reviewing the new draft would suggest the following:

* Cut the video after the `Open Policy Agent` slide (around 2:42).
* Then do closing/summary after that

**Comment by lxie123** [comment]
@djschny will cut and make the edit.

**Comment by djschny** [comment]
Here is an shortened version of the video as mentioned above:

https://drive.google.com/file/d/1mhA3dCt0yWAVZ9DvZWF-B_2yMeZ_Zdu7/view?usp=sharing

Note: While loading and working with the video I noticed the video provided is only 720p.

**Comment by lxie123** [comment]
Ready for marketing review.

**Comment by djschny** [comment]
@meghnam00 / @BoschemVM - since the video is back from editors, if it looks good for you all, then fine to publish at will as discussed in today's standup.
