### ISSUE TITLE
Educates Observability/Monitoring

### ISSUE THREAD

**Issue by jonasmit** [kube-academy/backlog#51]

**Comment by eitansuez** [comment]
i see this work breaking down into two parts:
- figure out how to expose # of workshopsessions as a metric to wavefront
- deploy an app that periodically calls lookup service to create a workshopsession and alerts (preferably to slack) if this operation fails

this should give us an idea for eduk8s load on the cluster over time, and an early warning if for some reason the ability to launch sessions stops working / starts failing.

basic idea is to deploy a pod onto the cluster that reports the desired metrics to wavefront.

**Comment by eitansuez** [comment]
will begin by prototyping a basic app that can be deployed to an eduk8s cluster that can expose workshopsessions as a metric.

**Comment by eitansuez** [comment]
https://gitlab.eng.vmware.com/sueze/eduk8smon

**Comment by djschny** [comment]
Progressing well, Eitan to meet with Bryan/Ryan to review get feedback.

**Comment by eitansuez** [comment]
there's still outstanding work to do regarding assessing average # of workshopsessions that a node can support, so have a better idea of capacity that cluster size can support.  but this should likely be a different story.  this story, i feel is done.  we now have a dashboard with information on workshopsessions over time and we have a probe that tests for successful workshop session creation and alerts to a slack channel if that operation fails.

**Comment by eitansuez** [comment]
closing issue.  dashboard has been working well, including alerts.
