### ISSUE TITLE
End to End Testing of Foundations Labs on Educates

### ISSUE THREAD

**Issue by jonasmit** [kube-academy/backlog#60]

**Comment by jonasmit** [comment]
@djschny - Can you provide the link to the staging site ?

- We will Assign reviewers and create PRs as needed

**Comment by djschny** [comment]
> @djschny - Can you provide the link to the staging site ?

Here is a link that pulls up the 5 courses - https://staging.kubeacademy.fixeldev.com/search/?q=kubernetes%20core%20concepts

Username: `kube`
Password: `kube`

**Comment by jonasmit** [comment]
Need folks to do end-to-end testing - in particular lab 4+

**Comment by eitansuez** [comment]
i have worked through all 10 labs and caught and fixed all issues i have encountered (educates environment, esp staging servers).
