### ISSUE TITLE
Code blocks overflow horizontal page layout

### ISSUE THREAD

**Issue by joemoore** [kube-academy/backlog#86]
Code blocks, or some combination of `<pre><code>` overflow and interfere with the the page layout. 

Steps to reproduce
1. Edit a lesson
2. add a very wide code block in markdown that is wider than the page layout. Any text will do as long as it is very wide. See screenshot.
3. Save
4. View page
5. Expected: Code block conforms to lesson width without obscuring or otherwise interfering with other page elements. Code block should be horizontally scrollable within "Description" area.
6. Actual Result: code block makes page as wide as the block. Page elements interfered with.

![pre-code-overflow](https://user-images.githubusercontent.com/13995/179832506-6b02578b-64c1-442f-a13d-8de9529262b9.png)

**Comment by joemoore** [comment]
Note that adding `overflow-x: scroll` to the `<pre>` element would fix this in CSS. See screenshots. 

#### Current 
Note code block overflowing Description area. 

![Screen Shot 2022-07-20 at 8 27 21 AM](https://user-images.githubusercontent.com/13995/180007974-463c2fc4-79ed-4623-930d-77bdceb8bc7c.png)

#### With proposed fix
Note scrollbar, code block contained within Description. 

![Screen Shot 2022-07-20 at 8 27 35 AM](https://user-images.githubusercontent.com/13995/180008001-6b7ab9c0-434e-4509-aa67-b82d6ddab175.png)

**Comment by djschny** [comment]
This has been fixed.
